### ISSUE TITLE
Nothing found on transifex

### ISSUE THREAD

**Issue by jiero** [ushahidi/Ushahidi-Localizations#106]
https://www.transifex.com/projects/p/ushahidi-localizations/ is gone.

**Comment by aoduor** [comment]
Hey @jiero, apologies for the confusion. We split this into two different projects as we launched Ushahidi v3 :).

Here you go:-

https://www.transifex.com/projects/p/ushahidi-v3
https://www.transifex.com/projects/p/ushahidi-v2

For more deets on translation, see http://www.ushahidi.com/support/get-involved
